twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        uploads_directory: '%uploads_directory%'
        google_ua: '%google_ua%'
        google_tag_ua: '%google_tag_ua%'
        google_key: '%google_key%'
        google_map_api_key: '%google_map_api_key%'
